#!/bin/bash

read() {
    section=$1
    item=$2

    val=`awk -F '=' '/\['${section}'\]/{a=1}a==1&&$1~/'${item}'/{print $0;exit}' ${config}`
    echo $val | sed "s/${item}\=//g"
}

status() {
    for key in ${list[@]}
    do
        name=$(read $key name)
        desc=$(read $key desc)
        service=$(read $key service)
        pid=`ps -aux | grep "${service}" | grep -v grep | awk 'NR==1 {print $2}'`

        if [ -z $pid ]; then
            id='Stopped'
        else
            detail=($(ps -eo pid,stat,etime,pcpu,pmem | grep $pid))
            case ${detail[1]} in
                'X') id='Stopped';;
                'Z') id='Stopped';;
                *) id="Running，${detail[0]}/${detail[2]}/${detail[3]}%/${detail[4]}%";;
            esac
        fi

        echo "${name}[${desc}] is ${id}。"
    done
}

start() {
    for key in ${list[@]}
    do
        name=$(read $key name)
        service=$(read $key service)
        log=$(read $key log)
        pid=`ps aux | grep "${service}" | grep -v grep | awk 'NR==1 {print $8}'`
        if [ -z $pid ]; then
            cd $(read $key work)
            su $(read setting user) -c "${service} >> ${log} &"
        else
            case $pid in
                'X') stop;;
                'Z') stop;;
            esac
        fi
    done
}

stop() {
    for key in ${list[@]}
    do
        service=$(read $key service)
        ps aux | grep "${service}" | grep -v grep | awk '{print $2}' | xargs kill -s 3 >/dev/null 2>&1
    done
}

restart() {
	stop
	start
}

daemon() {
    while true
    do
        start
        sleep 1
    done &
}

reload() {
    for key in ${list[@]}
    do
        service=$(read $key service)
        ps aux | grep "${service}" | grep -v grep | awk '{print $2}' | xargs kill -s 12 >/dev/null 2>&1
    done
}

recovery() {
    for key in ${list[@]}
    do
        service=$(read $key service)
        ps aux | grep "${service}" | grep -v grep | awk '{print $2}' | xargs kill -s 10 >/dev/null 2>&1
    done
}

if [ -z $1 ]; then
	echo 'Please enter then service for [stop|start|status|reload|recovery|restart|daemon]'
else
    task=`pwd`/$(dirname $0)'/task'
    config="${task}.config"

    OLD_IFS=$IFS
    IFS=','
    list=($(read setting listen))
    IFS=$OLD_IFS

    case $1 in
        'reload') reload;;
        'recovery') recovery;;
        'status') status;;
        'start') start;;
        'stop') stop;;
		'restart') restart;;
        'daemon') daemon;;
        *) echo 'Please enter then service for [stop|start|status|reload|recovery|restart|daemon]';;
    esac
fi