<?php
    return array(
        0x01=>array(
            'B'=>0x02,
            'F'=>'login'
        ),
        0x03=>array(
            'B'=>0x04,
            'F'=>'queryTicket'
        ),
        0x05=>array(
            'B'=>0x06,
            'F'=>'getTicket'
        ),
        0x07=>array(
            'B'=>0x08,
            'F'=>'getTicketExt'
        )
    );
